const centers = [
  {
    data: {
      profile: {
        id: 243081,
        name_with_title_and_determiner:
          "Centre de Vaccination Covid d'Illkirch",
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [],
      visit_motive_categories: [],
      visit_motives: [],
      agendas: [
        {
          id: 411095,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: null,
          anonymous: true,
          organization_id: 132512,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 164787,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 411097,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: null,
          anonymous: true,
          organization_id: 132512,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 164787,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-164787',
          address: '10b Avenue Achille Baumann',
          zipcode: '67400',
          city: 'Illkirch-Graffenstaden',
          floor: 0,
          latitude: 48.537467,
          longitude: 7.7227073,
          elevator: false,
          handicap: true,
          formal_name: "Centre de vaccination Covid-19 d'Illkirch",
          reception_info: null,
          name: "Centre de vaccination Covid-19 d'Illkirch",
          practice_ids: [164787],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 1471,
      has_new_patient_rule: false,
    },
  },
  {
    data: {
      profile: {
        id: 240971,
        name_with_title_and_determiner:
          'Centre de vaccination Covid-19 - CH de Haguenau',
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [
        { id: 5494, name: 'Vaccination COVID-19', kind: 'procedure' },
      ],
      visit_motive_categories: [],
      visit_motives: [
        {
          id: 2534819,
          name: '1ère injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: null,
          organization_id: 131041,
          speciality_id: 5494,
          ref_visit_motive_id: 6970,
          position: 1,
          telehealth: false,
          vaccination_days_range: 26,
          vaccination_motive: true,
          first_shot_motive: true,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
        {
          id: 2534820,
          name: '2nde injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: null,
          organization_id: 131041,
          speciality_id: 5494,
          ref_visit_motive_id: 6971,
          position: 2,
          telehealth: false,
          vaccination_days_range: 0,
          vaccination_motive: true,
          first_shot_motive: false,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
      ],
      agendas: [
        {
          id: 408787,
          booking_disabled: false,
          booking_temporary_disabled: false,
          landline_number: '03 88 06 31 76',
          anonymous: true,
          organization_id: 131041,
          visit_motive_ids_by_practice_id: { 163040: [2534819, 2534820] },
          visit_motive_ids: [2534819, 2534820],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163040,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 411953,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 06 31 76',
          anonymous: true,
          organization_id: 131041,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163040,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 407456,
          booking_disabled: false,
          booking_temporary_disabled: false,
          landline_number: '03 88 06 31 76',
          anonymous: true,
          organization_id: 131041,
          visit_motive_ids_by_practice_id: { 163040: [2534819, 2534820] },
          visit_motive_ids: [2534819, 2534820],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163040,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 407457,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 06 31 76',
          anonymous: true,
          organization_id: 131041,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163040,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-163040',
          address: '56 Avenue du Professeur René Leriche',
          zipcode: '67500',
          city: 'Haguenau',
          floor: null,
          latitude: 48.7997476,
          longitude: 7.7777446,
          elevator: false,
          handicap: true,
          formal_name: 'CH de Haguenau - Vaccination Covid',
          landline_number: '03 88 06 31 76',
          reception_info: null,
          name: 'CH de Haguenau - Vaccination Covid',
          practice_ids: [163040],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 2917,
      has_new_patient_rule: false,
    },
  },
  {
    data: {
      profile: {
        id: 243293,
        name_with_title_and_determiner:
          'Centre de vaccination anti-Covid de Lingolsheim',
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [
        { id: 5494, name: 'Vaccination COVID-19', kind: 'procedure' },
      ],
      visit_motive_categories: [],
      visit_motives: [
        {
          id: 2553174,
          name: '1ère injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: null,
          organization_id: 132860,
          speciality_id: 5494,
          ref_visit_motive_id: 6970,
          position: 1,
          telehealth: false,
          vaccination_days_range: 26,
          vaccination_motive: true,
          first_shot_motive: true,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
        {
          id: 2553175,
          name: '2nde injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: null,
          organization_id: 132860,
          speciality_id: 5494,
          ref_visit_motive_id: 6971,
          position: 2,
          telehealth: false,
          vaccination_days_range: 0,
          vaccination_motive: true,
          first_shot_motive: false,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
      ],
      agendas: [
        {
          id: 421169,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 69 06 40 09',
          anonymous: true,
          organization_id: 132860,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165239,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412728,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 69 06 40 09',
          anonymous: true,
          organization_id: 132860,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165239,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412727,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 69 06 40 09',
          anonymous: true,
          organization_id: 132860,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165239,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412269,
          booking_disabled: false,
          booking_temporary_disabled: false,
          landline_number: '03 69 06 40 09',
          anonymous: true,
          organization_id: 132860,
          visit_motive_ids_by_practice_id: { 165239: [2553174, 2553175] },
          visit_motive_ids: [2553174, 2553175],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165239,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412270,
          booking_disabled: false,
          booking_temporary_disabled: false,
          landline_number: '03 69 06 40 09',
          anonymous: true,
          organization_id: 132860,
          visit_motive_ids_by_practice_id: { 165239: [2553174, 2553175] },
          visit_motive_ids: [2553174, 2553175],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165239,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412271,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 69 06 40 09',
          anonymous: true,
          organization_id: 132860,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165239,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412272,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 69 06 40 09',
          anonymous: true,
          organization_id: 132860,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165239,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412273,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 69 06 40 09',
          anonymous: true,
          organization_id: 132860,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165239,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412274,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 69 06 40 09',
          anonymous: true,
          organization_id: 132860,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165239,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-165239',
          address: '27 Rue du Travail',
          zipcode: '67380',
          city: 'Lingolsheim',
          floor: null,
          latitude: 48.5616881,
          longitude: 7.6820474,
          elevator: false,
          handicap: false,
          formal_name:
            'Centre de vaccination anti-Covid-19 de Lingolsheim - Gymnase Im Sand ',
          landline_number: '03 69 06 40 09',
          reception_info: null,
          name:
            'Centre de vaccination anti-Covid-19 de Lingolsheim - Gymnase Im Sand ',
          practice_ids: [165239],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 1247,
      has_new_patient_rule: false,
    },
  },
  {
    data: {
      profile: {
        id: 241528,
        name_with_title_and_determiner:
          'Centre Vaccination Covid-19 - Groupe Hospitalier Sélestat-Obernai (GHSO) - Réservés aux professionnels de santé',
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [],
      visit_motive_categories: [],
      visit_motives: [],
      agendas: [
        {
          id: 408347,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 57 56 19',
          anonymous: true,
          organization_id: 131166,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163570,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 408642,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 57 56 19',
          anonymous: true,
          organization_id: 131166,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163571,
          speciality_id: 37,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 408641,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 57 56 19',
          anonymous: true,
          organization_id: 131166,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163570,
          speciality_id: 37,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 408349,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 89 22 42 07',
          anonymous: true,
          organization_id: 131166,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163572,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-163570',
          address: '23 Avenue Louis Pasteur',
          zipcode: '67600',
          city: 'Sélestat',
          floor: null,
          latitude: 48.2628237,
          longitude: 7.4355549,
          elevator: false,
          handicap: true,
          formal_name: 'Groupe Hospitalier Sélestat-Obernai - Site de Sélestat',
          landline_number: '03 88 57 56 19',
          reception_info: null,
          name: 'Groupe Hospitalier Sélestat-Obernai - Site de Sélestat',
          practice_ids: [163570],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
        {
          id: 'practice-163571',
          address: '3 Avenue du Maire Gillmann',
          zipcode: '67210',
          city: 'Obernai',
          floor: null,
          latitude: 48.4559834,
          longitude: 7.4880368,
          elevator: false,
          handicap: true,
          formal_name: 'Groupe Hospitalier Sélestat-Obernai - Site d’Obernai',
          landline_number: '03 88 57 56 19',
          reception_info: null,
          name: 'Groupe Hospitalier Sélestat-Obernai - Site d’Obernai',
          practice_ids: [163571],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
        {
          id: 'practice-163572',
          address: '17 Rue Jean Jacques Bock',
          zipcode: '68160',
          city: 'Sainte-Marie-aux-Mines',
          floor: null,
          latitude: 48.2452396,
          longitude: 7.175128,
          elevator: false,
          handicap: false,
          formal_name: 'Hôpital Intercommunal du Val d’Argent',
          reception_info: null,
          name: 'Hôpital Intercommunal du Val d’Argent',
          practice_ids: [163572],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 896,
      has_new_patient_rule: false,
    },
  },
  {
    data: {
      profile: {
        id: 243038,
        name_with_title_and_determiner:
          'CH Saverne - Centre de vaccination Covid-19 ( réservé aux professionnels de santé)',
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [
        { id: 5494, name: 'Vaccination COVID-19', kind: 'procedure' },
      ],
      visit_motive_categories: [],
      visit_motives: [
        {
          id: 2532715,
          name: '1ère injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: null,
          organization_id: 116340,
          speciality_id: 5494,
          ref_visit_motive_id: 6970,
          position: 1,
          telehealth: false,
          vaccination_days_range: 26,
          vaccination_motive: true,
          first_shot_motive: true,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
        {
          id: 2532716,
          name: '2nde injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: null,
          organization_id: 116340,
          speciality_id: 5494,
          ref_visit_motive_id: 6971,
          position: 2,
          telehealth: false,
          vaccination_days_range: 0,
          vaccination_motive: true,
          first_shot_motive: false,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
      ],
      agendas: [
        {
          id: 406975,
          booking_disabled: false,
          booking_temporary_disabled: false,
          landline_number: null,
          anonymous: true,
          organization_id: 116340,
          visit_motive_ids_by_practice_id: { 144302: [2532715, 2532716] },
          visit_motive_ids: [2532715, 2532716],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 144302,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 411160,
          booking_disabled: false,
          booking_temporary_disabled: false,
          landline_number: null,
          anonymous: true,
          organization_id: 116340,
          visit_motive_ids_by_practice_id: { 144302: [2532715, 2532716] },
          visit_motive_ids: [2532715, 2532716],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 144302,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-144302',
          address: '19 Côte de Saverne',
          zipcode: '67700',
          city: 'Saverne',
          floor: null,
          latitude: 48.7471314,
          longitude: 7.3513193,
          elevator: true,
          handicap: true,
          formal_name: 'CH Saverne - Centre Anti-Covid-19',
          reception_info: null,
          name: 'CH Saverne - Centre Anti-Covid-19',
          practice_ids: [144302],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 2288,
      has_new_patient_rule: false,
    },
  },
  {
    data: {
      profile: {
        id: 242678,
        name_with_title_and_determiner:
          'GH Saint-Vincent - Centre de vaccination Covid-19',
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [
        {
          id: 5494,
          name: 'Vaccination COVID-19',
          kind: 'procedure',
        },
      ],
      visit_motive_categories: [
        {
          id: 89325,
          name: 'Patients de plus de 75 ans',
          speciality_id: 5494,
        },
        {
          id: 89329,
          name: 'Professionnels de santé de plus de 50 ans',
          speciality_id: 5494,
        },
        {
          id: 91386,
          name: 'Personnes à risques',
          speciality_id: 5494,
        },
      ],
      visit_motives: [
        {
          id: 2527734,
          name: '1ère injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: 89325,
          organization_id: 130586,
          speciality_id: 5494,
          ref_visit_motive_id: 6970,
          position: 1,
          telehealth: false,
          vaccination_days_range: 26,
          vaccination_motive: true,
          first_shot_motive: true,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
        {
          id: 2527735,
          name: '2nde injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: 89325,
          organization_id: 130586,
          speciality_id: 5494,
          ref_visit_motive_id: 6971,
          position: 5,
          telehealth: false,
          vaccination_days_range: 0,
          vaccination_motive: true,
          first_shot_motive: false,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
        {
          id: 2553626,
          name: '1ère injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: 89329,
          organization_id: 130586,
          speciality_id: 5494,
          ref_visit_motive_id: 6970,
          position: 7,
          telehealth: false,
          vaccination_days_range: 26,
          vaccination_motive: true,
          first_shot_motive: true,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
        {
          id: 2553627,
          name: '2nde injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: 89329,
          organization_id: 130586,
          speciality_id: 5494,
          ref_visit_motive_id: 6971,
          position: 9,
          telehealth: false,
          vaccination_days_range: 0,
          vaccination_motive: true,
          first_shot_motive: false,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
        {
          id: 2588190,
          name: '1ère injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: 91386,
          organization_id: 130586,
          speciality_id: 5494,
          ref_visit_motive_id: 6970,
          position: 6,
          telehealth: false,
          vaccination_days_range: 26,
          vaccination_motive: true,
          first_shot_motive: true,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
        {
          id: 2588191,
          name: '2nde injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: 91386,
          organization_id: 130586,
          speciality_id: 5494,
          ref_visit_motive_id: 6971,
          position: 8,
          telehealth: false,
          vaccination_days_range: 0,
          vaccination_motive: true,
          first_shot_motive: false,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
      ],
      agendas: [
        {
          id: 418362,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: null,
          anonymous: false,
          organization_id: 130586,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 167405,
          speciality_id: 5494,
          practitioner_id: 29494995,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 406106,
          booking_disabled: false,
          booking_temporary_disabled: false,
          landline_number: '03 88 21 72 70',
          anonymous: true,
          organization_id: 130586,
          visit_motive_ids_by_practice_id: {
            162415: [2527734, 2527735, 2553626, 2553627, 2588190, 2588191],
          },
          visit_motive_ids: [
            2527734,
            2527735,
            2553626,
            2553627,
            2588190,
            2588191,
          ],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 162415,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 417282,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 21 72 70',
          anonymous: true,
          organization_id: 130586,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163151,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 417283,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 21 72 70',
          anonymous: true,
          organization_id: 130586,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 162415,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 417284,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: null,
          anonymous: true,
          organization_id: 130586,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 167406,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 417285,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: null,
          anonymous: true,
          organization_id: 130586,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 167405,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 407691,
          booking_disabled: false,
          booking_temporary_disabled: false,
          landline_number: '03 88 21 72 70',
          anonymous: true,
          organization_id: 130586,
          visit_motive_ids_by_practice_id: {
            163151: [2527734, 2527735, 2553626, 2553627, 2588190, 2588191],
          },
          visit_motive_ids: [
            2527734,
            2527735,
            2553626,
            2553627,
            2588190,
            2588191,
          ],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163151,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-162415',
          address: '29 Rue du Faubourg-National',
          zipcode: '67000',
          city: 'Strasbourg',
          floor: null,
          latitude: 48.5821746,
          longitude: 7.7355587,
          elevator: false,
          handicap: false,
          formal_name:
            'Groupe Hospitalier Saint Vincent - Clinique Sainte Barbe',
          landline_number: '03 88 21 72 70',
          reception_info: null,
          name: 'Groupe Hospitalier Saint Vincent - Clinique Sainte Barbe',
          practice_ids: [162415],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
        {
          id: 'practice-163151',
          address: '10 Rue des Forges',
          zipcode: '67130',
          city: 'Schirmeck',
          floor: null,
          latitude: 48.4830164,
          longitude: 7.2240843,
          elevator: false,
          handicap: false,
          formal_name: 'Groupe Hospitalier Saint Vincent - Clinique Saint Luc',
          landline_number: '03 88 21 72 70',
          reception_info: null,
          name: 'Groupe Hospitalier Saint Vincent - Clinique Saint Luc',
          practice_ids: [163151],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
        {
          id: 'practice-167406',
          address: 'Rue Philippe Thys',
          zipcode: '67000',
          city: 'Strasbourg',
          floor: null,
          latitude: 48.6141994,
          longitude: 7.7893406,
          elevator: false,
          handicap: false,
          formal_name:
            'Groupe Hospitalier Saint-Vincent - Clinique Sainte-Anne',
          reception_info: null,
          name: 'Groupe Hospitalier Saint-Vincent - Clinique Sainte-Anne',
          practice_ids: [167406],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
        {
          id: 'practice-167405',
          address: '11 Rue de la Toussaint',
          zipcode: '67000',
          city: 'Strasbourg',
          floor: null,
          latitude: 48.5869542,
          longitude: 7.7447803,
          elevator: false,
          handicap: false,
          formal_name:
            'Groupe Hospitalier Saint-Vincent - Clinique de la Toussaint',
          reception_info: null,
          name: 'Groupe Hospitalier Saint-Vincent - Clinique de la Toussaint',
          practice_ids: [167405],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 1368,
      has_new_patient_rule: false,
    },
  },
  {
    data: {
      profile: {
        id: 241528,
        name_with_title_and_determiner:
          'Centre Vaccination Covid-19 - Groupe Hospitalier Sélestat-Obernai (GHSO) - Réservés aux professionnels de santé',
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [],
      visit_motive_categories: [],
      visit_motives: [],
      agendas: [
        {
          id: 408347,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 57 56 19',
          anonymous: true,
          organization_id: 131166,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163570,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 408642,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 57 56 19',
          anonymous: true,
          organization_id: 131166,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163571,
          speciality_id: 37,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 408641,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 88 57 56 19',
          anonymous: true,
          organization_id: 131166,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163570,
          speciality_id: 37,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 408349,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '03 89 22 42 07',
          anonymous: true,
          organization_id: 131166,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 163572,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-163570',
          address: '23 Avenue Louis Pasteur',
          zipcode: '67600',
          city: 'Sélestat',
          floor: null,
          latitude: 48.2628237,
          longitude: 7.4355549,
          elevator: false,
          handicap: true,
          formal_name: 'Groupe Hospitalier Sélestat-Obernai - Site de Sélestat',
          landline_number: '03 88 57 56 19',
          reception_info: null,
          name: 'Groupe Hospitalier Sélestat-Obernai - Site de Sélestat',
          practice_ids: [163570],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
        {
          id: 'practice-163571',
          address: '3 Avenue du Maire Gillmann',
          zipcode: '67210',
          city: 'Obernai',
          floor: null,
          latitude: 48.4559834,
          longitude: 7.4880368,
          elevator: false,
          handicap: true,
          formal_name: 'Groupe Hospitalier Sélestat-Obernai - Site d’Obernai',
          landline_number: '03 88 57 56 19',
          reception_info: null,
          name: 'Groupe Hospitalier Sélestat-Obernai - Site d’Obernai',
          practice_ids: [163571],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
        {
          id: 'practice-163572',
          address: '17 Rue Jean Jacques Bock',
          zipcode: '68160',
          city: 'Sainte-Marie-aux-Mines',
          floor: null,
          latitude: 48.2452396,
          longitude: 7.175128,
          elevator: false,
          handicap: false,
          formal_name: 'Hôpital Intercommunal du Val d’Argent',
          reception_info: null,
          name: 'Hôpital Intercommunal du Val d’Argent',
          practice_ids: [163572],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 896,
      has_new_patient_rule: false,
    },
  },
  {
    data: {
      profile: {
        id: 243473,
        name_with_title_and_determiner:
          'Centre de vaccination Covid19 de Strasbourg',
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [
        {
          id: 5494,
          name: 'Vaccination COVID-19',
          kind: 'procedure',
        },
      ],
      visit_motive_categories: [],
      visit_motives: [],
      agendas: [
        {
          id: 412674,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '0 800 60 90 90',
          anonymous: true,
          organization_id: 132980,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165399,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412675,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '0 800 60 90 90',
          anonymous: true,
          organization_id: 132980,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165399,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412676,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '0 800 60 90 90',
          anonymous: true,
          organization_id: 132980,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165399,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412677,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '0 800 60 90 90',
          anonymous: true,
          organization_id: 132980,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165399,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 412678,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '0 800 60 90 90',
          anonymous: true,
          organization_id: 132980,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165399,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 413517,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '0 800 60 90 90',
          anonymous: true,
          organization_id: 132980,
          visit_motive_ids_by_practice_id: {
            165399: [],
          },
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 165399,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-165399',
          address: '1 Place du Maréchal de Lattre de Tassigny',
          zipcode: '67000',
          city: 'Strasbourg',
          floor: null,
          latitude: 48.5763967,
          longitude: 7.7532797,
          elevator: false,
          handicap: true,
          formal_name: 'Centre de vaccination Covid-19 de Strasbourg',
          landline_number: '0 800 60 90 90',
          reception_info: null,
          name: 'Centre de vaccination Covid-19 de Strasbourg',
          practice_ids: [165399],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 6003,
      has_new_patient_rule: false,
    },
  },
  {
    data: {
      profile: {
        id: 243060,
        name_with_title_and_determiner:
          'Centre de vaccination Covid-19 - Mossig et Vignoble',
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [],
      visit_motive_categories: [],
      visit_motives: [],
      agendas: [
        {
          id: 411492,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '09 70 81 81 61',
          anonymous: true,
          organization_id: 132597,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 164920,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 411493,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '09 70 81 81 61',
          anonymous: true,
          organization_id: 132597,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 164920,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
        {
          id: 411490,
          booking_disabled: true,
          booking_temporary_disabled: false,
          landline_number: '09 70 81 81 61',
          anonymous: true,
          organization_id: 132597,
          visit_motive_ids_by_practice_id: {},
          visit_motive_ids: [],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 164920,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-164920',
          address: '1 Rue de Cosswiller',
          zipcode: '67310',
          city: 'Wasselonne',
          floor: null,
          latitude: 48.6372441,
          longitude: 7.4434854,
          elevator: false,
          handicap: true,
          formal_name: 'Espace Saint Laurent salle polyvalente',
          landline_number: '09 70 81 81 61',
          reception_info: null,
          name: 'Espace Saint Laurent salle polyvalente',
          practice_ids: [164920],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 1900,
      has_new_patient_rule: false,
    },
  },
  {
    data: {
      profile: {
        id: 242657,
        name_with_title_and_determiner:
          'Centre de vaccination COVID - CH de Wissembourg',
        speciality: null,
        organization: true,
        redirect_url: null,
      },
      specialities: [
        {
          id: 5494,
          name: 'Vaccination COVID-19',
          kind: 'procedure',
        },
      ],
      visit_motive_categories: [],
      visit_motives: [
        {
          id: 2548456,
          name: '1ère injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: null,
          organization_id: 132382,
          speciality_id: 5494,
          ref_visit_motive_id: 6970,
          position: 1,
          telehealth: false,
          vaccination_days_range: 26,
          vaccination_motive: true,
          first_shot_motive: true,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
        {
          id: 2548457,
          name: '2nde injection vaccin COVID-19 (Pfizer-BioNTech)',
          visit_motive_category_id: null,
          organization_id: 132382,
          speciality_id: 5494,
          ref_visit_motive_id: 6971,
          position: 2,
          telehealth: false,
          vaccination_days_range: 0,
          vaccination_motive: true,
          first_shot_motive: false,
          allow_new_patients: true,
          allow_new_patients_on_insurance_sector: true,
          configurations: null,
        },
      ],
      agendas: [
        {
          id: 410775,
          booking_disabled: false,
          booking_temporary_disabled: false,
          landline_number: '03 88 54 13 13',
          anonymous: true,
          organization_id: 132382,
          visit_motive_ids_by_practice_id: {
            164638: [2548456, 2548457],
          },
          visit_motive_ids: [2548456, 2548457],
          visit_motive_ids_only_for_doctors: null,
          practice_id: 164638,
          speciality_id: 5494,
          practitioner_id: null,
          insurance_sector_enabled: false,
          equipment_agendas_required: false,
        },
      ],
      places: [
        {
          id: 'practice-164638',
          address: '24 Route de Weiler',
          zipcode: '67160',
          city: 'Wissembourg',
          floor: null,
          latitude: 49.0402086,
          longitude: 7.9339496,
          elevator: true,
          handicap: true,
          formal_name: 'CH de Wissembourg',
          landline_number: '03 88 54 13 13',
          reception_info: null,
          name: 'CH de Wissembourg',
          practice_ids: [164638],
          is_aphp: false,
          aphp_url: 'http://www.aphp.fr/contenu/combien-ca-coute',
        },
      ],
      practitioners: [],
      availabilities_preview_compatible: false,
      vaccination_center: true,
      number_future_vaccinations: 1991,
      has_new_patient_rule: false,
    },
  },
]

module.exports = { centers }
